name: Run pytest

# Allow to trigger the workflow manually (e.g. when deps changes)
on: [push, workflow_dispatch]

jobs:
  pytest-job:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        # Uncomment to cache of pip dependencies (if tests run too slowly)
        # cache: pip

    - name: Install dependencies via pip
      run: |
        pip install --upgrade pip
        pip --version
        pip install -r requirements.txt --upgrade
        pip install .
        pip freeze

    - name: Run tests  # The -n auto comes from pytest-xdist, and enables running tests in parallel
      run: pytest -vv -n auto
